### PR TITLE
Fix utf8 bom issue

### LINKED ISSUE #12: Support files which starts with BOM unicode character
**Issue**
We are trying to format our feature files, but looks like it is not possible if it's encoded with e.g UTF-8 or Unicode. 

**Update**
With further investigations, it turned out that the root of the problem is not the Encoding.
It seems the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) character is the culprit in this case.

**How to reproduce**
With BOM 
[with-bom-character.zip](https://github.com/antham/ghokin/files/3068609/with-bom-character.zip)
1. ghokin.exe check with-bom-character.feature
2. Fails with Parser error

Without BOM
[without-bom-character.zip](https://github.com/antham/ghokin/files/3068610/without-bom-character.zip)
1. ghokin.exe check without-bom-character.feature
2. Works fine

### PR DESCRIPTION
**Pull request by antham**
Fix #12

### CODE REVIEW

File: ghokin/file_manager.go [hunk 1]
```diff
@@ -201,3 +218,26 @@ func findFeatureFiles(rootPath string, extensions []string) ([]string, error) {
 
 	return files, nil
 }
+
+// skipBom moves file pointer after BOM if one is found and returns it
+func skipBom(file *os.File) ([]byte, error) {
+	bom := []byte{'\xef', '\xbb', '\xbf'}
+
+	file.Seek(0, io.SeekStart)
```
Comment (golangcibot) [inline ghokin/file_manager.go]: Error return value of `file.Seek` is not checked (from `errcheck`)

File: ghokin/file_manager.go [hunk 2]
```diff
@@ -201,3 +218,26 @@ func findFeatureFiles(rootPath string, extensions []string) ([]string, error) {
...
+
+	buffer := make([]byte, len(bom))
+
+	if n, err := file.Read(buffer); err != nil || n < len(bom) {
+		file.Seek(0, io.SeekStart)
```
Comment (golangcibot) [inline ghokin/file_manager.go]: Error return value of `file.Seek` is not checked (from `errcheck`)

File: ghokin/file_manager.go [hunk 3]
```diff
@@ -201,3 +218,26 @@ func findFeatureFiles(rootPath string, extensions []string) ([]string, error) {
...
+
+		return []byte{}, err
+	}
+
+	if bytes.Compare(bom, buffer) == 0 {
+		return bom, nil
+	}
+
+	file.Seek(0, io.SeekStart)
```
Comment (golangcibot) [inline ghokin/file_manager.go]: Error return value of `file.Seek` is not checked (from `errcheck`)

File: ghokin/file_manager.go [hunk 4]
```diff
@@ -201,3 +218,26 @@ func findFeatureFiles(rootPath string, extensions []string) ([]string, error) {
...
+
+	buffer := make([]byte, len(bom))
+
+	if n, err := file.Read(buffer); err != nil || n < len(bom) {
+		file.Seek(0, io.SeekStart)
+
+		return []byte{}, err
+	}
+
+	if bytes.Compare(bom, buffer) == 0 {
```
Comment (golangcibot) [inline ghokin/file_manager.go]: S1004: should use bytes.Equal(bom, buffer) instead (from `gosimple`)
